import_elements_query = ["""
MERGE (e:Element {name: "Pt"})
MERGE (e1:Element {name: "C"})
MERGE (m:Material:CarbonSupport {})
"""]
import_data_query = ["""
LOAD CSV WITH HEADERS FROM 'file:///InsituMeas.csv' AS line
CREATE (d:Device:FuelCell {name: line.Decal_Id})
MERGE (m1:Material:Catalyst {name: line.Catalyst})
MERGE (m2:Material:CoatingSubstrate {name: line.Coating_substrate})
MERGE (m3:Material:TransferSubstrate {name: line.Transfer_substrate})
MERGE (m4:Material:Ionomer {name: line.Ionomer})
MERGE (c:Component:Membrane {name: line.Membrane})
MERGE (c1:Component:Anode {name: line.Anode})
MERGE (c2:Component:GDL {name: line.GDL})
MERGE (c3:Component:Station {name: line.Station})
CREATE (p:Process:FabricationProcess {uid: randomUUID()})
CREATE (m5:Material:Catalyst {name: "CatalystPowder", type: "CatalystInkPrecursor"})
CREATE(m1)-[r:PROCESSED] -> (p)
CREATE(m:Material:CarbonSupport {})-[r1:PROCESSED] -> (p)
CREATE(p)-[r2:YIELDS_MAT] -> (m5)
CREATE (m6:Material:Catalyst {name: "MilledCatalystPowder", type: "CatalystInkPrecursor"})
CREATE (p1:Process:FabricationProcess {uid: randomUUID()})
MERGE (pa:Parameter {type: "MillingTime", value: line.Drymill_time_hrs })
CREATE(m5)-[r3:PROCESSED] -> (p1)-[r4:USED_PARAMETER]->(pa)
CREATE(p1)-[r5:YIELDS_MAT] -> (m6)
CREATE (p2:Process:FabricationProcess {uid: randomUUID()})
CREATE(m6)-[r6:PROCESSED] -> (p2)
CREATE(m4)-[r7:PROCESSED] -> (p2)
CREATE(m7:Material:CatalystInk {name: "CatalalystInk", type:"CatalystInk"})
CREATE(p2)-[r8:YIELDS_MAT] -> (m7)
MERGE(m8:Material:CoatingSubstrate {name: line.Coating_substrate})
MERGE(m9:Material:TransferSubstrate {name: line.Transfer_substrate})
CREATE (p3:Process:FabricationProcess {uid: randomUUID()})
CREATE(m8)-[r9:PROCESSED] -> (p3)
CREATE(m9)-[r10:PROCESSED] -> (p3)
CREATE(m7)-[r11:PROCESSED] -> (p3)
CREATE(m10:Component:CatalysLayer {name: "CatalystLayer", type: "CatalystLayer"})
CREATE(p3)-[r12:YIELDS_COMP] -> (m10)
CREATE (p4:Process:FabricationProcess {uid: randomUUID()})
CREATE(m10)-[r13:PROCESSED] -> (p4)
CREATE(c)-[r14:PROCESSED] -> (p4)
CREATE(c1)-[r15:PROCESSED] -> (p4)
CREATE(m12:Component:MEA {name: "MEA", type: "MEA"})
CREATE(p4)-[r16:YIELDS_COMP] -> (m12)
MERGE (pa1:Parameter {type: "HotPressed"})
CREATE(p4)-[r17:USED_PARAMETER] -> (pa1)
CREATE (p5:Process:FabricationProcess {uid: randomUUID()})
CREATE(m12)-[r18:PROCESSED] -> (p5)
CREATE(c2)-[r19:PROCESSED] -> (p5)
CREATE(c3)-[r20:PROCESSED] -> (p5)
CREATE(p5)-[r21:YIELDS_DEV] -> (d)
CREATE (pa2:Parameter {type: "I/C", value: line.IC})
CREATE (me:Measurement {uid: randomUUID()})
CREATE (me1:Measurement {uid: randomUUID()})
CREATE(m10)-[r22:MEASURED] -> (me)
CREATE(p3)-[r24:USED_PARAMETER] -> (pa2)
MERGE (pr:Property {type: "PtLoading/cm2", value: line.Pt_loading_mgcm2geo})
CREATE(me)-[r25:YIELDS_PROP] -> (pr)

CREATE (me2:Measurement {uid: randomUUID()})
CREATE (me3:Measurement {uid: randomUUID()})
CREATE (me4:Measurement {uid: randomUUID()})
CREATE (me5:Measurement {uid: randomUUID()})
CREATE (me6:Measurement {uid: randomUUID()})
CREATE (me7:Measurement {uid: randomUUID()})
CREATE (me8:Measurement {uid: randomUUID()})
CREATE (me9:Measurement {uid: randomUUID()})
CREATE (me10:Measurement {uid: randomUUID()})
CREATE (me11:Measurement {uid: randomUUID()})
CREATE (me12:Measurement {uid: randomUUID()})
CREATE (me13:Measurement {uid: randomUUID()})
CREATE (me14:Measurement {uid: randomUUID()})
CREATE (me15:Measurement {uid: randomUUID()})
CREATE (me16:Measurement {uid: randomUUID()})
CREATE (me17:Measurement {uid: randomUUID()})
CREATE (me18:Measurement {uid: randomUUID()})
CREATE (me19:Measurement {uid: randomUUID()})
CREATE (me20:Measurement {uid: randomUUID()})
CREATE (me21:Measurement {uid: randomUUID()})
CREATE (me22:Measurement {uid: randomUUID()})
CREATE (me23:Measurement {uid: randomUUID()})
CREATE (me24:Measurement {uid: randomUUID()})
CREATE (me25:Measurement {uid: randomUUID()})
CREATE (me26:Measurement {uid: randomUUID()})
CREATE (me27:Measurement {uid: randomUUID()})
CREATE (me28:Measurement {uid: randomUUID()})
CREATE (me29:Measurement {uid: randomUUID()})
CREATE (me30:Measurement {uid: randomUUID()})
CREATE (me31:Measurement {uid: randomUUID()})
CREATE (me32:Measurement {uid: randomUUID()})
CREATE (me33:Measurement {uid: randomUUID()})
CREATE (me34:Measurement {uid: randomUUID()})
CREATE (me35:Measurement {uid: randomUUID()})
CREATE (me36:Measurement {uid: randomUUID()})
CREATE (me37:Measurement {uid: randomUUID()})

CREATE(d)-[r26:MEASURED] -> (me2)
CREATE(d)-[r27:MEASURED] -> (me3)
CREATE(d)-[r28:MEASURED] -> (me4)
CREATE(d)-[r29:MEASURED] -> (me5)
CREATE(d)-[r30:MEASURED] -> (me6)
CREATE(d)-[r31:MEASURED] -> (me7)
CREATE(d)-[r32:MEASURED] -> (me8)
CREATE(d)-[r33:MEASURED] -> (me9)
CREATE(d)-[r34:MEASURED] -> (me10)
CREATE(d)-[r35:MEASURED] -> (me11)
CREATE(d)-[r36:MEASURED] -> (me12)
CREATE(d)-[r37:MEASURED] -> (me13)
CREATE(d)-[r38:MEASURED] -> (me14)
CREATE(d)-[r39:MEASURED] -> (me15)
CREATE(d)-[r40:MEASURED] -> (me16)
CREATE(d)-[r41:MEASURED] -> (me17)
CREATE(d)-[r42:MEASURED] -> (me18)
CREATE(d)-[r43:MEASURED] -> (me19)
CREATE(d)-[r44:MEASURED] -> (me20)
CREATE(d)-[r45:MEASURED] -> (me21)
CREATE(d)-[r46:MEASURED] -> (me22)
CREATE(d)-[r47:MEASURED] -> (me23)
CREATE(d)-[r48:MEASURED] -> (me24)
CREATE(d)-[r49:MEASURED] -> (me25)
CREATE(d)-[r50:MEASURED] -> (me26)
CREATE(d)-[r51:MEASURED] -> (me27)
CREATE(d)-[r52:MEASURED] -> (me28)
CREATE(d)-[r53:MEASURED] -> (me29)
CREATE(d)-[r54:MEASURED] -> (me30)
CREATE(d)-[r55:MEASURED] -> (me31)
CREATE(d)-[r56:MEASURED] -> (me32)
CREATE(d)-[r57:MEASURED] -> (me33)
CREATE(d)-[r58:MEASURED] -> (me34)
CREATE(d)-[r59:MEASURED] -> (me35)
CREATE(d)-[r60:MEASURED] -> (me36)
CREATE(d)-[r61:MEASURED] -> (me37)

MERGE (pr3:Property {type: "HOT2.4V", value: line.HOT_24_V})
MERGE (pr4:Property {type: "HOT2.1V", value: line.HOT_21_V})
MERGE (pr5:Property {type: "HOT1.9V", value: line.HOT_19_V})
MERGE (pr6:Property {type: "HOT1.7V", value: line.HOT_17_V})
MERGE (pr7:Property {type: "HOT1.5V", value: line.HOT_15_V})
MERGE (pr8:Property {type: "HOT1.2V", value: line.HOT_12_V})
MERGE (pr9:Property {type: "HOT1.0V", value: line.HOT_10_V})
MERGE (pr10:Property {type: "HOT0.6V", value: line.HOT_06_V})
MERGE (pr11:Property {type: "HOT0.2V", value: line.HOT_02_V})
MERGE (pr12:Property {type: "HOT0.1V", value: line.HOT_01_V})
MERGE (pr13:Property {type: "HOT0.05V", value: line.HOT_005_V})
MERGE (pr14:Property {type: "HOT_OCV_V", value: line.HOT_OCV_V})
MERGE (pr15:Property {type: "NOC2.4V", value: line.NOC_24_V})
MERGE (pr16:Property {type: "NOC2.1V", value: line.NOC_21_V})
MERGE (pr17:Property {type: "NOC1.9V", value: line.NOC_19_V})
MERGE (pr18:Property {type: "NOC1.7V", value: line.NOC_17_V})
MERGE (pr19:Property {type: "NOC1.5V", value: line.NOC_15_V})
MERGE (pr20:Property {type: "NOC1.2V", value: line.NOC_12_V})
MERGE (pr21:Property {type: "NOC1.0V", value: line.NOC_10_V})
MERGE (pr22:Property {type: "NOC0.6V", value: line.NOC_06_V})
MERGE (pr23:Property {type: "NOC0.2V", value: line.NOC_02_V})
MERGE (pr24:Property {type: "NOC0.1V", value: line.NOC_01_V})
MERGE (pr25:Property {type: "NOC0.05V", value: line.NOC_005_V})
MERGE (pr26:Property {type: "NOC_OCV_V", value: line.NOC_OCV_V})
MERGE (pr27:Property {type: "WUP2.4V", value: line.WUP_24_V})
MERGE (pr28:Property {type: "WUP2.1V", value: line.WUP_21_V})
MERGE (pr29:Property {type: "WUP1.9V", value: line.WUP_19_V})
MERGE (pr30:Property {type: "WUP1.7V", value: line.WUP_17_V})
MERGE (pr31:Property {type: "WUP1.5V", value: line.WUP_15_V})
MERGE (pr32:Property {type: "WUP1.2V", value: line.WUP_12_V})
MERGE (pr33:Property {type: "WUP1.0V", value: line.WUP_10_V})
MERGE (pr34:Property {type: "WUP0.6V", value: line.WUP_06_V})
MERGE (pr35:Property {type: "WUP0.2V", value: line.WUP_02_V})
MERGE (pr36:Property {type: "WUP0.1V", value: line.WUP_01_V})
MERGE (pr37:Property {type: "WUP0.05V", value: line.WUP_005_V})
MERGE (pr38:Property {type: "WUP_OCV_V", value: line.WUP_OCV_V})

CREATE(me2)-[r62:YIELDS_PROP] -> (pr38)
CREATE(me3)-[r63:YIELDS_PROP] -> (pr3)
CREATE(me4)-[r64:YIELDS_PROP] -> (pr4)
CREATE(me5)-[r65:YIELDS_PROP] -> (pr5)
CREATE(me6)-[r66:YIELDS_PROP] -> (pr6)
CREATE(me7)-[r67:YIELDS_PROP] -> (pr7)
CREATE(me8)-[r68:YIELDS_PROP] -> (pr8)
CREATE(me9)-[r69:YIELDS_PROP] -> (pr9)
CREATE(me10)-[r70:YIELDS_PROP] -> (pr10)
CREATE(me11)-[r71:YIELDS_PROP] -> (pr11)
CREATE(me12)-[r72:YIELDS_PROP] -> (pr12)
CREATE(me13)-[r73:YIELDS_PROP] -> (pr13)
CREATE(me14)-[r74:YIELDS_PROP] -> (pr14)
CREATE(me15)-[r75:YIELDS_PROP] -> (pr15)
CREATE(me16)-[r76:YIELDS_PROP] -> (pr16)
CREATE(me17)-[r77:YIELDS_PROP] -> (pr17)
CREATE(me18)-[r78:YIELDS_PROP] -> (pr18)
CREATE(me19)-[r79:YIELDS_PROP] -> (pr19)
CREATE(me20)-[r80:YIELDS_PROP] -> (pr20)
CREATE(me21)-[r81:YIELDS_PROP] -> (pr21)
CREATE(me22)-[r82:YIELDS_PROP] -> (pr22)
CREATE(me23)-[r83:YIELDS_PROP] -> (pr23)
CREATE(me24)-[r84:YIELDS_PROP] -> (pr24)
CREATE(me25)-[r85:YIELDS_PROP] -> (pr25)
CREATE(me26)-[r86:YIELDS_PROP] -> (pr26)
CREATE(me27)-[r87:YIELDS_PROP] -> (pr27)
CREATE(me28)-[r88:YIELDS_PROP] -> (pr28)
CREATE(me29)-[r89:YIELDS_PROP] -> (pr29)
CREATE(me30)-[r90:YIELDS_PROP] -> (pr30)
CREATE(me31)-[r91:YIELDS_PROP] -> (pr31)
CREATE(me32)-[r92:YIELDS_PROP] -> (pr32)
CREATE(me33)-[r93:YIELDS_PROP] -> (pr33)
CREATE(me34)-[r94:YIELDS_PROP] -> (pr34)
CREATE(me35)-[r95:YIELDS_PROP] -> (pr35)
CREATE(me36)-[r96:YIELDS_PROP] -> (pr36)
CREATE(me37)-[r97:YIELDS_PROP] -> (pr37)
"""]

test = """
MERGE(ps:Process {Substrate: line.Transfer_substrate})
MERGE(m: Properties {name="Subjective_Crack_rating", value: line.Subjective_Crack_rating, type="Volumetric"})
MERGE(o: Process {name: "Hot_pressed", line.Hot_pressed})
MERGE(p: Property {name: "", line.Hot_pressed})
MERGE(q: Process {substrate: line.Coating_substrate})
MERGE(r: Process {Time: line.Drymill_time_hrs})
MERGE(s: Process {Temp: line.Drying_temp_deg_C})
MERGE(t: Process {Name: line.Catalyst})
MERGE(u: Process {Name: line.Ionomer})
MERGE(pp: Process {Name: line.IC})
MERGE(pq: Process {Loading: line.Pt_loading_mgcm2geo})
MERGE(pr: Properties {Thickness: line.SEM_CCL_thickness_µm, unit: "micrometer"})
MERGE(pt: Properties {PV: line.Calculated_PV_based_on_SEM_thickness_cm3cm2geo})
MERGE(pu: Properties {PV: line.Calculated_porosity_based_on_SEM_thickness_, unit: "%"})
MERGE(pr)-[a:calculated_from] -> (pt)
MERGE(pr)-[b:calculated_from] -> (pu)
MERGE(n)-[c:has_property] -> (pr)
MERGE(n)-[d:used] -> (ps)
MERGE(n)-[r:has_property] -> (m)
MERGE(n)-[s:pressed_with] -> (o)
MERGE(n)-[t:coated_with] -> (p)
MERGE(n)-[u:drymilled_with] -> (q)
MERGE(n)-[v:dried_with] -> (nn)
MERGE(n)-[w:used_catalyst] -> (mm)
MERGE(n)-[x:used_solvant] -> (po)
MERGE(n)-[y:used_cat_iono_ratio] -> (pp)
MERGE(n)-[z:used_catalyst_loading] -> (pq)
"""
