import_data_query = """
LOAD CSV WITH HEADERS FROM 'file:///data.csv' AS row
MERGE (a:Component {cid: row.Decal_ID, type: "Catalyst_Layer"})
MERGE (b:Process {name: "Transfer_Substrate"})
MERGE (c:Material {name: row.Decal_ID})
"""
test = """
MERGE (ps:Process {Substrate: row.Transfer_substrate})
MERGE (m:Properties {name = "Subjective_Crack_rating", value: row.Subjective_Crack_rating, type = "Volumetric"})
MERGE (o:Process {name: "Hot_pressed", row.Hot_pressed})
MERGE (o:Property {name: "", row.Hot_pressed})
MERGE (p:Process {substrate: row.Coating_substrate})
MERGE (q:Process {Time: row.Drymill_time_hrs})
MERGE (nn:Process {Temp: row.Drying_temp_deg_C})
MERGE (mm:Process {Name: row.Catalyst})
MERGE (po:Process {Name: row.Ionomer})
MERGE (pp:Process {Name: row.IC})
MERGE (pq:Process {Loading: row.Pt_loading_mgcm2geo})
MERGE (pr:Properties {Thickness: row.SEM_CCL_thickness_µm, unit: "micrometer"})
MERGE (pt:Properties {PV: row.Calculated_PV_based_on_SEM_thickness_cm3cm2geo})
MERGE (pu:Properties {PV: row.Calculated_porosity_based_on_SEM_thickness_, unit: "%"})
MERGE (pr)-[a:calculated_from]->(pt)
MERGE (pr)-[b:calculated_from]->(pu)
MERGE (n)-[c:has_property]->(pr)
MERGE (n)-[d:used]->(ps)
MERGE (n)-[r:has_property]->(m)
MERGE (n)-[s:pressed_with]->(o)
MERGE (n)-[t:coated_with]->(p)
MERGE (n)-[u:drymilled_with]->(q)
MERGE (n)-[v:dried_with]->(nn)
MERGE (n)-[w:used_catalyst]->(mm)
MERGE (n)-[x:used_solvant]->(po)
MERGE (n)-[y:used_cat_iono_ratio]->(pp)
MERGE (n)-[z:used_catalyst_loading]->(pq)
"""
