# Generated by Django 3.1.13 on 2022-01-14 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JobFieldCluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sco_id', models.BigIntegerField()),
                ('job_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clusters', to='skills.jobfield')),
            ],
        ),
    ]
