# Generated by Django 3.1.13 on 2022-04-04 13:08

from django.db import migrations
from neomodel import db

def delete_matching_enabled(apps, schema_editor):
    results, meta = db.cypher_query("MATCH (n:WorkProfile) REMOVE n.matching_enabled")



class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(delete_matching_enabled),
    ]
