# Generated by Django 3.1.13 on 2022-05-03 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0003_auto_20220502_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchedCandidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.UUIDField()),
                ('full_name', models.CharField(max_length=100)),
                ('profile_url', models.URLField()),
                ('email', models.CharField(max_length=100)),
            ],
        ),
    ]
