# Generated by Django 3.1.13 on 2022-05-18 15:22

#from django import db
from neomodel import db 
from django.db import migrations


def add_pause_to_jobadvert(apps, schema_editor):
    results, meta = db.cypher_query(
        '''MATCH (job:JobAdvert) set job.pause=false'''
    )
        

class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0004_matchedcandidate'),
    ]

    operations = [
        migrations.RunPython(add_pause_to_jobadvert)
    ]
