# Generated by Django 3.1.13 on 2022-07-01 21:27

from django.db import migrations
from neomodel import db 

def user_skill_to_skill_model(apps, schema_editor):
    results, meta = db.cypher_query(
        '''MATCH (skill:Skill) set skill.user_skill=false'''
    )

class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0005_auto_20220518_1722'),
    ]

    operations = [
        migrations.RunPython(user_skill_to_skill_model)
    ]
