# Generated by Django 3.2.13 on 2022-08-01 12:05

from django.db import migrations
from neomodel import db


def add_imported_unchecked(apps, schema_editor):

    with db.write_transaction:

        db.cypher_query(
            '''
            MATCH (wp:ExternalWorkProfile)
            SET wp.imported_unchecked=false
            '''
        )


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0007_auto_20220728_1117'),
    ]

    operations = [
        migrations.RunPython(add_imported_unchecked)
    ]