# Generated by Django 3.2.13 on 2022-08-09 08:00

from django.db import migrations
from neomodel import db


def remove_functions_domains(apps, schema_editor):
    with db.write_transaction:
        db.cypher_query(
            'MATCH (func:Function) DETACH DELETE func'
        )
        db.cypher_query(
            'MATCH (dom:Domain) DETACH DELETE dom'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0009_auto_20220809_0931'),
    ]

    operations = [
        migrations.RunPython(remove_functions_domains)
    ]
