# Generated by Django 3.2.13 on 2022-11-03 15:26

from django.db import migrations
from neomodel import db



def create_slugs(apps, schema_editor):

    results, meta = db.cypher_query(
        '''
        CALL apoc.periodic.iterate(
            "MATCH (company:Company)-[:HAS_OPEN_POSITION]->(job:JobAdvert) RETURN job, company.name as company_name",
            "SET job.slug=apoc.text.slug(company_name+'-'+job.title)",
            {batchSize:50000}
        )
        '''
    )

    # some jobs might not have companies connected
    results, meta = db.cypher_query(
        '''
            MATCH (job:JobAdvert)
            WHERE NOT EXISTS(job.slug)
            SET job.slug=apoc.text.slug(job.title)
        '''
    )


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0010_auto_20220809_1000'),
    ]

    operations = [
        migrations.RunPython(create_slugs)
    ]
