# Generated by Django 3.2.16 on 2022-11-10 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0011_auto_20221103_1626'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MatchedCandidate',
        ),
    ]
