from models import SCO
from skills import JobField

entries = [
    ("Gastronomie / Hotellerie / Tourismus", "Gastroservice-Jobs"),
    ("Gastronomie / Hotellerie / Tourismus", "Hotel-Jobs"),
    ("Gastronomie / Hotellerie / Tourismus", "Gastro-Jobs"),
    ("Gastronomie / Hotellerie / Tourismus", "Tourismus-Jobs"),
    ("Gastronomie / Hotellerie / Tourismus", "Küchen-Jobs"),
    ("Transport / Verkehr", "Transport-Jobs"),
    ("Transport / Verkehr", "Fahrer-Jobs"),
    ("Transport / Verkehr", "Logistik-Jobs"),
    ("Transport / Verkehr", "Disponenten-Jobs"),
    ("Transport / Verkehr", "Verkehrs-Jobs"),
    ("Diverse", "Mikro-Jobs"),
    ("Diverse", "Gering qualifizierte Jobs"),
    ("Diverse", "Hauswirtschafts-Jobs"),
    ("Management / Führung", "Projektmanagement-Jobs"),
    ("Management / Führung", "Führungs-Jobs"),
    ("Management / Führung", "Managementsupport-Jobs"),
    ("Diverse", "Öko-Jobs"),
    ("Diverse", "Sport-Jobs"),
    ("Diverse", "Stylisten-Jobs"),
    ("Administration / Verwaltung", "Sekretariats-Jobs"),
    ("Administration / Verwaltung", "Assistenten-Jobs"),
    ("Administration / Verwaltung", "Verwaltungs-Jobs"),
    ("Administration / Verwaltung", "Sachbearbeiter-Jobs"),
    ("Administration / Verwaltung", "Kaufmännische Jobs"),
    ("Administration / Verwaltung", "Ökonomie-Jobs"),
    ("Medizin / Gesundheitswesen", "Pflege-Jobs"),
    ("Medizin / Gesundheitswesen", "Ärzte-Jobs"),
    ("Medizin / Gesundheitswesen", "Psychologie-Jobs"),
    ("Medizin / Gesundheitswesen", "Medizinische Assistenz-Jobs"),
    ("Medizin / Gesundheitswesen", "Therapeuten-Jobs"),
    ("Medizin / Gesundheitswesen", "Tierpflege-Jobs"),
    ("Medizin / Gesundheitswesen", "Zahnmedizin-Jobs"),
    ("Bau / Handwerk / Immobilien", "Handwerker-Jobs"),
    ("Bau / Handwerk / Immobilien", "Reinigungs-Jobs"),
    ("Bau / Handwerk / Immobilien", "Gärtner-Jobs"),
    ("Bau / Handwerk / Immobilien", "Bau-Jobs"),
    ("Bau / Handwerk / Immobilien", "Immobilien-Jobs"),
    ("Bau / Handwerk / Immobilien", "Maler-Jobs"),
    ("Bau / Handwerk / Immobilien", "Spengler-Jobs"),
    ("Bau / Handwerk / Immobilien", "Montage-Jobs"),
    ("Bau / Handwerk / Immobilien", "Holzbearbeitungs-Jobs"),
    ("Bau / Handwerk / Immobilien", "Geomatik-Jobs"),
    ("Bau / Handwerk / Immobilien", "HLK-Jobs"),
    ("Bau / Handwerk / Immobilien", "Architekten-Jobs"),
    ("Bau / Handwerk / Immobilien", "Instrumentenbau-Jobs"),
    ("Technik / Ingenieurwesen", "Lebensmittel-Jobs"),
    ("Technik / Ingenieurwesen", "Forscher-Jobs"),
    ("Technik / Ingenieurwesen", "Ingenieur-Jobs"),
    ("Technik / Ingenieurwesen", "Techniker-Jobs"),
    ("Technik / Ingenieurwesen", "Metall-Jobs"),
    ("Technik / Ingenieurwesen", "Servicetechniker-Jobs"),
    ("Technik / Ingenieurwesen", "Mechaniker-Jobs"),
    ("Technik / Ingenieurwesen", "Elektrotechnik-Jobs"),
    ("Technik / Ingenieurwesen", "CAD/CAM-Jobs"),
    ("Technik / Ingenieurwesen", "Konstrukteurs-Jobs"),
    ("Technik / Ingenieurwesen", "Textil-Jobs"),
    ("Technik / Ingenieurwesen", "Drucker-Jobs"),
    ("Informatik", "Informatiker-Jobs"),
    ("Informatik", "Internet-Jobs"),
    ("Informatik", "Software-Jobs"),
    ("Informatik", "Programmier-Jobs"),
    ("Informatik", "Software-Testing-Jobs"),
    ("Informatik", "Systemspezialisten-Jobs"),
    ("Informatik", "SAP-Jobs"),
    ("Informatik", "Telekom-Jobs"),
    ("Informatik", "IT-Administratoren-Jobs"),
    ("Informatik", "IT-Support-Jobs"),
    ("Informatik", "IT-Sicherheits-Jobs"),
    ("Informatik", "Multimedia-Jobs"),
    ("Informatik", "Datenbank-Jobs"),
    ("Informatik", "ERP-Jobs"),
    ("Informatik", "Informationsmanagement-Jobs"),
    ("Informatik", "Entwicklungs-Jobs"),
    ("Recht / Beratung", "Berater-Jobs"),
    ("Recht / Beratung", "Legal-Jobs"),
    ("Recht / Beratung", "Treuhand-Jobs"),
    ("Recht / Beratung", "Steuer-Jobs"),
    ("Recht / Beratung", "Analysten-Jobs"),
    ("Recht / Beratung", "Patent-Jobs"),
    ("Verkauf / Einkauf / Kundenberatung", "Detailhandel-Jobs"),
    ("Verkauf / Einkauf / Kundenberatung", "Verkaufs-Jobs"),
    ("Verkauf / Einkauf / Kundenberatung", "Call Center-Jobs"),
    ("Verkauf / Einkauf / Kundenberatung", "Direktmarketing-Jobs"),
    ("Verkauf / Einkauf / Kundenberatung", "Aussendienst-Jobs"),
    ("Verkauf / Einkauf / Kundenberatung", "Kundenbetreuungs-Jobs"),
    ("Verkauf / Einkauf / Kundenberatung", "Verkaufsinnendienst-Jobs"),
    ("Verkauf / Einkauf / Kundenberatung", "Produktmanagement-Jobs"),
    ("Verkauf / Einkauf / Kundenberatung", "Export-Jobs"),
    ("Verkauf / Einkauf / Kundenberatung", "Einkäufer-Jobs"),
    ("Chemie / Pharmazie", "Pharma-Jobs"),
    ("Chemie / Pharmazie", "Labor-Jobs"),
    ("Chemie / Pharmazie", "Chemiker-Jobs"),
    ("Chemie / Pharmazie", "Biologie-Jobs"),
    ("Schutz / Sicherheit", "Schutz-Jobs"),
    ("Finanz- / Rechnungswesen", "Buchhalter-Jobs"),
    ("Finanz- / Rechnungswesen", "Revisions-Jobs"),
    ("Finanz- / Rechnungswesen", "Controller-Jobs"),
    ("Schutz / Sicherheit", "Inspektoren-Jobs"),
    ("Schutz / Sicherheit", "Sicherheits-Jobs"),
    ("Produktion / Operations", "Produktions-Jobs"),
    ("Bank / Versicherung", "Finanz-Jobs"),
    ("Bank / Versicherung", "Versicherungs-Jobs"),
    ("Bank / Versicherung", "Private Banking-Jobs"),
    ("Bank / Versicherung", "Nichtlebensversicherungs-Jobs"),
    ("Bank / Versicherung", "Kredit-Jobs"),
    ("Bank / Versicherung", "Investment Banking-Jobs"),
    ("Bank / Versicherung", "Banking-Jobs"),
    ("Bank / Versicherung", "Händler-Jobs"),
    ("Bank / Versicherung", "Riskmanagement-Jobs"),
    ("Bank / Versicherung", "Personenversicherungs-Jobs"),
    ("Bank / Versicherung", "Sozialversicherungs-Jobs"),
    ("Bank / Versicherung", "Sachversicherungs-Jobs"),
    ("Produktion / Operations", "Verpackungs-Jobs"),
    ("Produktion / Operations", "Qualitätsmanagement-Jobs"),
    ("Produktion / Operations", "Operator-Jobs"),
    ("Personal / Organisation / Bildung", "Ausbildungs-Jobs"),
    ("Personal / Organisation / Bildung", "Personalmanagement-Jobs"),
    ("Personal / Organisation / Bildung", "Koordinatoren-Jobs"),
    ("Personal / Organisation / Bildung", "Organisations-Jobs"),
    ("Personal / Organisation / Bildung", "Rekrutierungs-Jobs"),
    ("Marketing / Kommunikation / Medien", "Marketing-Jobs"),
    ("Marketing / Kommunikation / Medien", "Redaktions-Jobs"),
    ("Marketing / Kommunikation / Medien", "Online-Marketing-Jobs"),
    ("Marketing / Kommunikation / Medien", "Journalismus-Jobs"),
    ("Marketing / Kommunikation / Medien", "Marktforschungs-Jobs"),
    ("Marketing / Kommunikation / Medien", "Media-Jobs"),
    ("Marketing / Kommunikation / Medien", "TV-Jobs"),
    ("Marketing / Kommunikation / Medien", "Marketingkommunikations-Jobs"),
    ("Marketing / Kommunikation / Medien", "Eventmanagement-Jobs"),
    ("Marketing / Kommunikation / Medien", "Werbe-Jobs"),
    ("Marketing / Kommunikation / Medien", "Autoren-Jobs"),
    ("Marketing / Kommunikation / Medien", "Verlags-Jobs"),
    ("Marketing / Kommunikation / Medien", "Fotografen-Jobs"),
    ("Marketing / Kommunikation / Medien", "Dokumentalisten-Jobs"),
    ("Non-Profit / Kunst / Soziales", "Sozial-Jobs"),
    ("Non-Profit / Kunst / Soziales", "Theater-Jobs"),
    ("Non-Profit / Kunst / Soziales", "Künstler-Jobs"),
    ("Non-Profit / Kunst / Soziales", "Bibliothekar-Jobs"),
    ("Non-Profit / Kunst / Soziales", "Kinderbetreuungs-Jobs"),
    ("Non-Profit / Kunst / Soziales", "Museums-Jobs"),
    ("Non-Profit / Kunst / Soziales", "Seelsorger-Jobs"),
    ("Planung / Design", "Designer-Jobs"),
    ("Planung / Design", "Planer-Jobs"),
    ("Planung / Design", "Zeichner-Jobs"),
]

def add_entries(entries):
    for field_name, sco_name in entries:

        field, created = JobField.objects.get_or_create(name=field_name)
        sco = SCO.objects.filter(name=sco_name).first()
        field.clusters.create(sco_id=sco.id)

