import_elements_query = ["""
MERGE (e:Element {name: "Pt"})
MERGE (e1:Element {name: "C"})
MERGE (m:Manufactured:ManufacturedMaterial:CarbonSupport {})
"""]
import_fabians_data_query = ["""
LOAD CSV WITH HEADERS FROM 'file:///simulation1.csv' AS line
CREATE (mol:Virtual:Matter:Molecule{uid: randomUUID(), nAtoms: line.nAtoms, weight: line.MolecularWeightgmol})
CREATE (me:Virtual:Process:Measurement {uid: randomUUID()})
CREATE(mol)-[r:measured] -> (me)
MERGE (pr:PhysicalDimension:Property {type: "SinglePointEnergy"})
CREATE(me)-[r1:yieldsQuant {value: line.SinglePointEnergyau}] -> (pr)

MERGE (pr2:PhysicalDimension:Property {type: "DipoleMoment"})
CREATE(me)-[r2:yieldsQuant {value: line.DipoleMomentDebye}] -> (pr2)

MERGE (pr3:PhysicalDimension:Property {type: "HOMO-1"})
CREATE(me)-[r3:yieldsQuant {value: line.HOMOIkJmol}] -> (pr3)

MERGE (pr4:PhysicalDimension:Property {type: "HOMO"})
CREATE(me)-[r4:yieldsQuant {value: line.HOMOkJmol}] -> (pr4)

MERGE (pr5:PhysicalDimension:Property {type: "LUMO"})
CREATE(me)-[r5:yieldsQuant {value: line.LUMOkJmol}] -> (pr5)

MERGE (pr6:PhysicalDimension:Property {type: "LUMO+1"})
CREATE(me)-[r6:yieldsQuant {value: line.LUMOIkJmol}] -> (pr6)

"""]
import_data_query = ["""
LOAD CSV WITH HEADERS FROM 'file:///InsituMeas.csv' AS line

CREATE (d:Manufactured:ManufacturedDevice:FuelCell {uid: randomUUID()})
MERGE (cat:Manufactured:ManufacturedMaterial:Catalyst {name: line.Catalyst})
MERGE (coatsub:Manufactured:ManufacturedMaterial:CoatingSubstrate {name: line.Coating_substrate})
MERGE (transsub:Manufactured:ManufacturedMaterial:TransferSubstrate {name: line.Transfer_substrate})
MERGE (membrane:Manufactured:ManufacturedComponent:Membrane {name: line.Membrane})
MERGE (anode:Manufactured:ManufacturedComponent:Anode {name: line.Anode})
MERGE (gdl:Manufactured:ManufacturedComponent:GDL {name: line.GDL})
MERGE (station:Manufactured:ManufacturedComponent:Station {name: line.Station})
MERGE (solvent:ChemicalEntity:Molecule:Solvent {name: "H2O"})
MERGE (ionomer:ChemicalEntity:Molecule:Ionomer {name: "Nafion"})
MERGE (plate:Manufactured:ManufacturedComponent:BipolarPlate {name: "NA"})
MERGE(carbonsupp:Manufactured:ManufacturedMaterial:CarbonBasedMaterial {uid: randomUUID(), type: "CarbonSupport"})

CREATE (catInkPr:Process:Manufacturing:CatalystInkManufacturing {uid: randomUUID(), type: "CatalystInkManufacturing"})
CREATE(cat)-[r1:isManufacturingInput] -> (catInkPr)
CREATE(solvent)-[r2:isManufacturingInput] -> (catInkPr)
CREATE(Ionomer)-[r3:isManufacturingInput] -> (catInkPr)
CREATE(carbonsupp)-[r4:isManufacturingInput] -> (catInkPr)
Merge (pa2:Process:Parameter {type: "I/C", value : line.IC})
CREATE(p3)-[r46:usesParameter {value: line.IC}] -> (pa2)
CREATE(catInk:ManufacturedMaterial:CatalystInk {uid: randomUUID()})
CREATE(catInkPr)-[r5:hasManufacturingOutput] -> (catInk)

CREATE (catInksubPr:Process:ManufacturingSubProcess {uid: randomUUID(), type: "DryMilling"})
CREATE (catInksubPr1:Process:ManufacturingSubProcess{uid: randomUUID(), type: "Mixing"})
CREATE(catInkPr)-[r6:subProcess] -> (catInksubPr)
CREATE(carbonsupp)-[r7:isManufacturingInput] -> (catInksubPr)
CREATE(catalyst)-[r8:isManufacturingInput] -> (catInksubPr)
MERGE (milltime:PhysicalDimension:Parameter {type: "MillingTime", value: line.Drymill_time_hrs})
CREATE(catInksubPr)-[r9:hasParameterInput ]->(milltime)
CREATE (catpowder:ManufacturedMaterial:Catalyst {type: "CatalystPowder"})
CREATE(catInkPr)-[r10:hasManufacturingOutput] -> (catpowder)
CREATE(catpowder)-[r11:isManufacturingInput]->(catInksubPr1)
CREATE(ionomer)-[r12:isManufacturingInput]->(catInksubPr1)
CREATE(Solvent)-[r13:isManufacturingInput]->(catInksubPr1)
CREATE(catInksubPr1)-[r14:hasManufacturingOutput]->(catInk)
CREATE(catInksubPr)-[r15:subProcess] -> (catInksubPr1)
CREATE(catInksubPr1)-[r16:subProcess] -> (catInkPr)
MERGE (dryingtime:PhysicalDimension:Parameter {type: "DryingTemp", value: line.Drying_temp_deg_C})
MERGE (hotpress:PhysicalDimension:Parameter {type: "HotPressTemp", value: 150})
CREATE (catAppPr:Process:Manufacturing:CatalysLayerManufacturing {uid: randomUUID(), type: "CatalystApplication"})
CREATE (ccm:ManufacturedMaterial:CatalystLayer {uid: randomUUID(), type: "CatalystCoatedMembrane"})
CREATE (catAppsubPr:Process:ManufacturingSubProcess{uid: randomUUID(), type: "Coating"})
CREATE(anode)-[r17:isManufacturingInput] -> (catAppPr)
CREATE(membrane)-[r45:isManufacturingInput] -> (catAppPr)
CREATE(transsub)-[r18:isManufacturingInput] -> (catAppPr)
CREATE(coatsub)-[r19:isManufacturingInput] -> (catAppPr)
CREATE(catInk)-[r23:isManufacturingInput] -> (catAppPr)
CREATE(catAppPr)-[r34:hasManufacturingOutput]->(ccm)

CREATE(catAppPr)-[r20:hasParameterInput]->(hotpress)
CREATE(catAppPr)-[r21:hasParameterInput]->(dryingtime)

CREATE(catAppPr)-[r22:subProcess] -> (catAppsubPr)
CREATE(transsub)-[r24:isManufacturingInput] -> (catAppsubPr)
CREATE(catInk)-[r25:isManufacturingInput] -> (catAppsubPr)
CREATE (catAppsubPr1:Process:ManufacturingSubProcess{uid: randomUUID(), type: "Drying"})
CREATE (catlayerInt:ManufacturedMaterial:CatalystLayer {type: "CatalystTransferSubstrate"})
CREATE(catAppsubPr)-[r27:hasManufacturingOutput]->(catlayerInt)
CREATE(catlayerInt)-[r28:isManufacturingInput] -> (catAppsubPr1)
CREATE(catAppsubPr)-[r26:subProcess] -> (catAppsubPr1)
CREATE(catAppsubPr1)-[r29:hasParameterInput]->(dryingtime)
CREATE (catlayerIntdry:ManufacturedMaterial:CatalystLayer {type: "CatalystTransferSubstrate"})
CREATE(catAppsubPr1)-[r30:hasManufacturingOutput]->(catlayerIntdry)
CREATE (catAppsubPr2:Process:ManufacturingSubProcess{uid: randomUUID(), type: "HotPress"})
CREATE(catlayerIntdry)-[r31:isManufacturingInput] -> (catAppsubPr2)
CREATE(catAppsubPr1)-[r37:subProcess] -> (catAppsubPr2)
CREATE(membrane)-[r32:isManufacturingInput] -> (catAppsubPr2)
CREATE(catAppsubPr2)-[r33:hasParameterInput]->(hotpress)
CREATE(catAppsubPr1)-[r35:hasManufacturingOutput]->(ccm)
CREATE(catAppsubPr2)-[r36:subProcess] -> (catAppPr)





CREATE (meaPr:Process:Manufacturing:MEAManufacturing {uid: randomUUID(), type: "CCMGDL"})
CREATE(ccm)-[r38:isManufacturingInput] -> (meaPr)
CREATE(gdl)-[r39:isManufacturingInput] -> (meaPr)
CREATE(mea:Manufactured:ManufacturedComponent:MEA {uid: randomUUID(), type: "MEA"})
CREATE(meaPr)-[r40:hasManufacturingOutput]->(mea)


CREATE (fuelcellPr:Process:Manufacturing:FuelCellAssembly {uid: randomUUID()})
CREATE(station)-[r41:isManufacturingInput] -> (fuelcellPr)
CREATE(mea)-[r42:isManufacturingInput] -> (fuelcellPr)
CREATE(plate)-[r43:isManufacturingInput] -> (fuelcellPr)
CREATE(fuelcellPr)-[r44:hasManufacturingOutput] -> (d)




CREATE (me21:Process:Measurement {uid: randomUUID()})
CREATE(d)-[r100:measured] -> (me21)
CREATE(me21)-[r621:yieldsQuant {value: line.HOT_24_V}] -> (pr31)
MERGE (pa301:PhysicalDimension:Parameter {type: "Voltage"})
CREATE(me21)-[r2261:usesParameter{value: 2.4}] -> (pa301)

CREATE (me221:Process:Measurement {uid: randomUUID()})
CREATE(d)-[r2621:measured] -> (me221)
CREATE(me221)-[r6221:yieldsQuant {value: line.NOC_24_V}] -> (pr321)
MERGE (pa321:PhysicalDimension:Parameter {type: "Voltage"})
CREATE(me221)-[r22621:usesParameter{value: 2.4}] -> (pa321)

CREATE (me231:Process:Measurement {uid: randomUUID()})
CREATE(d)-[r2631:measured] -> (me231)
CREATE(me231)-[r6231:yieldsQuant {value: line.WUP_24_V}] -> (pr331)
MERGE (pa331:PhysicalDimension:Parameter {type: "Voltage"})
CREATE(me231)-[r22631:usesParameter{value: 2.4}] -> (pa331)

CREATE (me22:Process:Measurement {uid: randomUUID()})
CREATE(d)-[r262:measured] -> (me22)
CREATE(me22)-[r622:yieldsQuant {value: line.HOT_24_V}] -> (pr31)
MERGE (pa302:PhysicalDimension:Parameter {type: "Voltage"})
CREATE(me22)-[r2262:usesParameter{value: 2.1}] -> (pa302)

CREATE (me222:Process:Measurement {uid: randomUUID()})
CREATE(d)-[r2622:measured] -> (me222)
CREATE(me222)-[r6222:yieldsQuant {value: line.NOC_24_V}] -> (pr321)
MERGE (pa322:PhysicalDimension:Parameter {type: "Voltage"})
CREATE(me222)-[r22622:usesParameter{value: 2.1}] -> (pa322)

CREATE (me232:Process:Measurement {uid: randomUUID()})
CREATE(d)-[r2632:measured] -> (me232)
CREATE(me232)-[r6232:yieldsQuant {value: line.WUP_24_V}] -> (pr331)
MERGE (pa332:PhysicalDimension:Parameter {type: "Voltage"})
CREATE(me232)-[r22632:usesParameter{value: 2.1}] -> (pa332)

CREATE (me23:Process:Measurement {uid: randomUUID()})
CREATE(d)-[r263:measured] -> (me23)
CREATE(me23)-[r623:yieldsQuant {value: line.HOT_24_V}] -> (pr31)
MERGE (pa303:PhysicalDimension:Parameter {type: "Voltage"})
CREATE(me23)-[r2263:usesParameter{value: 1.9}] -> (pa303)

CREATE (me223:Process:Measurement {uid: randomUUID()})
CREATE(d)-[r2623:measured] -> (me223)
CREATE(me223)-[r6223:yieldsQuant {value: line.NOC_24_V}] -> (pr321)
MERGE (pa323:PhysicalDimension:Parameter {type: "Voltage"})
CREATE(me223)-[r22623:usesParameter{value: 1.9}] -> (pa323)

CREATE (me233:Process:Measurement {uid: randomUUID()})
CREATE(d)-[r2633:measured] -> (me233)
CREATE(me233)-[r6233:yieldsQuant {value: line.WUP_24_V}] -> (pr331)
MERGE (pa333:PhysicalDimension:Parameter {type: "Voltage"})
CREATE(me233)-[r22633:usesParameter{value: 1.9}] -> (pa333)

CREATE (me24:Process:Measurement {uid: randomUUID()})
CREATE(d)-[r264:measured] -> (me24)
CREATE(me24)-[r624:yieldsQuant {value: line.HOT_24_V}] -> (pr31)
MERGE (pa304:PhysicalDimension:Parameter {type: "Voltage"})
CREATE(me24)-[r2264:usesParameter{value: 1.7}] -> (pa304)

CREATE (me224:Process:Measurement {uid: randomUUID()})
CREATE(d)-[r2624:measured] -> (me224)
CREATE(me224)-[r6224:yieldsQuant {value: line.NOC_24_V}] -> (pr321)
MERGE (pa324:PhysicalDimension:Parameter {type: "Voltage"})
CREATE(me224)-[r22624:usesParameter{value: 1.7}] -> (pa324)

CREATE (me234:Process:Measurement {uid: randomUUID()})
CREATE(d)-[r2634:measured] -> (me234)
CREATE(me234)-[r6234:yieldsQuant {value: line.WUP_24_V}] -> (pr331)
MERGE (pa334:PhysicalDimension:Parameter {type: "Voltage"})
CREATE(me234)-[r22634:usesParameter{value: 1.7}] -> (pa334)

CREATE (me25:Process:Measurement {uid: randomUUID()})
CREATE(d)-[r265:measured] -> (me25)
CREATE(me25)-[r625:yieldsQuant {value: line.HOT_24_V}] -> (pr31)
MERGE (pa305:PhysicalDimension:Parameter {type: "Voltage"})
CREATE(me25)-[r2265:usesParameter{value: 1.5}] -> (pa305)

CREATE (me225:Process:Measurement {uid: randomUUID()})
CREATE(d)-[r2625:measured] -> (me225)
CREATE(me225)-[r6225:yieldsQuant {value: line.NOC_24_V}] -> (pr321)
MERGE (pa325:PhysicalDimension:Parameter {type: "Voltage"})
CREATE(me225)-[r22625:usesParameter{value: 1.5}] -> (pa325)

CREATE (me235:Process:Measurement {uid: randomUUID()})
CREATE(d)-[r2635:measured] -> (me235)
CREATE(me235)-[r6235:yieldsQuant {value: line.WUP_24_V}] -> (pr331)
MERGE (pa335:PhysicalDimension:Parameter {type: "Voltage"})
CREATE(me235)-[r22635:usesParameter{value: 1.5}] -> (pa335)

CREATE (me26:Process:Measurement {uid: randomUUID()})
CREATE(d)-[r266:measured] -> (me26)
CREATE(me26)-[r626:yieldsQuant {value: line.HOT_24_V}] -> (pr31)
MERGE (pa306:PhysicalDimension:Parameter {type: "Voltage"})
CREATE(me26)-[r2266:usesParameter{value: 1.2}] -> (pa306)

CREATE (me226:Process:Measurement {uid: randomUUID()})
CREATE(d)-[r2626:measured] -> (me226)
CREATE(me226)-[r6226:yieldsQuant {value: line.NOC_24_V}] -> (pr321)
MERGE (pa326:PhysicalDimension:Parameter {type: "Voltage"})
CREATE(me226)-[r22626:usesParameter{value: 1.2}] -> (pa326)

CREATE (me236:Process:Measurement {uid: randomUUID()})
CREATE(d)-[r2636:measured] -> (me236)
CREATE(me236)-[r6236:yieldsQuant {value: line.WUP_24_V}] -> (pr331)
MERGE (pa336:PhysicalDimension:Parameter {type: "Voltage"})
CREATE(me236)-[r22636:usesParameter{value: 1.2}] -> (pa336)

CREATE (me27:Process:Measurement {uid: randomUUID()})
CREATE(d)-[r267:measured] -> (me27)
CREATE(me27)-[r627:yieldsQuant {value: line.HOT_24_V}] -> (pr31)
MERGE (pa307:PhysicalDimension:Parameter {type: "Voltage"})
CREATE(me27)-[r2267:usesParameter{value: 1.0}] -> (pa307)

CREATE (me227:Process:Measurement {uid: randomUUID()})
CREATE(d)-[r2627:measured] -> (me227)
CREATE(me227)-[r6227:yieldsQuant {value: line.NOC_24_V}] -> (pr321)
MERGE (pa327:PhysicalDimension:Parameter {type: "Voltage"})
CREATE(me227)-[r22627:usesParameter{value: 1.0}] -> (pa327)

CREATE (me237:Process:Measurement {uid: randomUUID()})
CREATE(d)-[r2637:measured] -> (me237)
CREATE(me237)-[r6237:yieldsQuant {value: line.WUP_24_V}] -> (pr331)
MERGE (pa337:PhysicalDimension:Parameter {type: "Voltage"})
CREATE(me237)-[r22637:usesParameter{value: 1.0}] -> (pa337)

CREATE (me28:Process:Measurement {uid: randomUUID()})
CREATE(d)-[r268:measured] -> (me28)
CREATE(me28)-[r628:yieldsQuant {value: line.HOT_24_V}] -> (pr31)
MERGE (pa308:PhysicalDimension:Parameter {type: "Voltage"})
CREATE(me28)-[r2268:usesParameter{value: 0.6}] -> (pa308)

CREATE (me228:Process:Measurement {uid: randomUUID()})
CREATE(d)-[r2628:measured] -> (me228)
CREATE(me228)-[r6228:yieldsQuant {value: line.NOC_24_V}] -> (pr321)
MERGE (pa328:PhysicalDimension:Parameter {type: "Voltage"})
CREATE(me228)-[r22628:usesParameter{value: 0.6}] -> (pa328)

CREATE (me238:Process:Measurement {uid: randomUUID()})
CREATE(d)-[r2638:measured] -> (me238)
CREATE(me238)-[r6238:yieldsQuant {value: line.WUP_24_V}] -> (pr331)
MERGE (pa338:PhysicalDimension:Parameter {type: "Voltage"})
CREATE(me238)-[r22638:usesParameter{value: 0.6}] -> (pa338)

CREATE (me29:Process:Measurement {uid: randomUUID()})
CREATE(d)-[r269:measured] -> (me29)
CREATE(me29)-[r629:yieldsQuant {value: line.HOT_24_V}] -> (pr31)
MERGE (pa309:PhysicalDimension:Parameter {type: "Voltage"})
CREATE(me29)-[r2269:usesParameter{value: 0.2}] -> (pa309)

CREATE (me229:Process:Measurement {uid: randomUUID()})
CREATE(d)-[r2629:measured] -> (me229)
CREATE(me229)-[r6229:yieldsQuant {value: line.NOC_24_V}] -> (pr321)
MERGE (pa329:PhysicalDimension:Parameter {type: "Voltage"})
CREATE(me229)-[r22629:usesParameter{value: 0.2}] -> (pa329)

CREATE (me239:Process:Measurement {uid: randomUUID()})
CREATE(d)-[r2639:measured] -> (me239)
CREATE(me239)-[r6239:yieldsQuant {value: line.WUP_24_V}] -> (pr331)
MERGE (pa339:PhysicalDimension:Parameter {type: "Voltage"})
CREATE(me239)-[r22639:usesParameter{value: 0.2}] -> (pa339)

CREATE (me2a1:Process:Measurement {uid: randomUUID()})
CREATE(d)-[r26a1:measured] -> (me2a1)
CREATE(me2a1)-[r62a1:yieldsQuant {value: line.HOT_24_V}] -> (pr31)
MERGE (pa30a1:PhysicalDimension:Parameter {type: "Voltage"})
CREATE(me2a1)-[r226a1:usesParameter{value: 0.1}] -> (pa30a1)

CREATE (me22a1:Process:Measurement {uid: randomUUID()})
CREATE(d)-[r262a1:measured] -> (me22a1)
CREATE(me22a1)-[r622a1:yieldsQuant {value: line.NOC_24_V}] -> (pr321)
MERGE (pa32a1:PhysicalDimension:Parameter {type: "Voltage"})
CREATE(me22a1)-[r2262a1:usesParameter{value: 0.1}] -> (pa32a1)

CREATE (me23a1:Process:Measurement {uid: randomUUID()})
CREATE(d)-[r263a1:measured] -> (me23a1)
CREATE(me23a1)-[r623a1:yieldsQuant {value: line.WUP_24_V}] -> (pr331)
MERGE (pa33a1:PhysicalDimension:Parameter {type: "Voltage"})
CREATE(me23a1)-[r2263a1:usesParameter{value: 0.1}] -> (pa33a1)

CREATE (me2a2:Process:Measurement {uid: randomUUID()})
CREATE(d)-[r26a2:measured] -> (me2a2)
CREATE(me2a2)-[r62a2:yieldsQuant {value: line.HOT_24_V}] -> (pr31)
MERGE (pa30a2:PhysicalDimension:Parameter {type: "Voltage"})
CREATE(me2a2)-[r226a2:usesParameter{value: 0.05}] -> (pa30a2)

CREATE (me22a2:Process:Measurement {uid: randomUUID()})
CREATE(d)-[r262a2:measured] -> (me22a2)
CREATE(me22a2)-[r622a2:yieldsQuant {value: line.NOC_24_V}] -> (pr321)
MERGE (pa32a2:PhysicalDimension:Parameter {type: "Voltage"})
CREATE(me22a2)-[r2262a2:usesParameter{value: 0.05}] -> (pa32a2)

CREATE (me23a2:Process:Measurement {uid: randomUUID()})
CREATE(d)-[r263a2:measured] -> (me23a2)
CREATE(me23a2)-[r623a2:yieldsQuant {value: line.WUP_24_V}] -> (pr331)
MERGE (pa33a2:PhysicalDimension:Parameter {type: "Voltage"})
CREATE(me23a2)-[r2263a2:usesParameter{value: 0.05}] -> (pa33a2)

CREATE (me2a3:Process:Measurement {uid: randomUUID()})
CREATE(d)-[r26a3:measured] -> (me2a3)
CREATE(me2a3)-[r62a3:yieldsQuant {value: line.HOT_24_V}] -> (pr31)
MERGE (pa30a3:PhysicalDimension:Parameter {type: "Voltage"})
CREATE(me2a3)-[r226a3:usesParameter{value: 0}] -> (pa30a3)

CREATE (me22a3:Process:Measurement {uid: randomUUID()})
CREATE(d)-[r262a3:measured] -> (me22a3)
CREATE(me22a3)-[r622a3:yieldsQuant {value: line.NOC_24_V}] -> (pr321)
MERGE (pa32a3:PhysicalDimension:Parameter {type: "Voltage"})
CREATE(me22a3)-[r2262a3:usesParameter{value: 0}] -> (pa32a3)

CREATE (me23a3:Process:Measurement {uid: randomUUID()})
CREATE(d)-[r263a3:measured] -> (me23a3)
CREATE(me23a3)-[r623a3:yieldsQuant {value: line.WUP_24_V}] -> (pr331)
MERGE (pa33a3:PhysicalDimension:Parameter {type: "Voltage"})
CREATE(me23a3)-[r2263a3:usesParameter{value: 0}] -> (pa33a3)


"""]

test = """
MERGE(ps:Process {Substrate: line.Transfer_substrate})
MERGE(m: Properties {name="Subjective_Crack_rating", value: line.Subjective_Crack_rating, type="Volumetric"})
MERGE(o: Process {name: "Hot_pressed", line.Hot_pressed})
MERGE(p: PhysicalDimension:Property {name: "", line.Hot_pressed})
MERGE(q: Process {substrate: line.Coating_substrate})
MERGE(r: Process {Time: line.Drymill_time_hrs})
MERGE(s: Process {Temp: line.Drying_temp_deg_C})
MERGE(t: Process {Name: line.Catalyst})
MERGE(u: Process {Name: line.Ionomer})
MERGE(pp: Process {Name: line.IC})
MERGE(pq: Process {Loading: line.Pt_loading_mgcm2geo})
MERGE(pr: Properties {Thickness: line.SEM_CCL_thickness_µm, unit: "micrometer"})
MERGE(pt: Properties {PV: line.Calculated_PV_based_on_SEM_thickness_cm3cm2geo})
MERGE(pu: Properties {PV: line.Calculated_porosity_based_on_SEM_thickness_, unit: "%"})
MERGE(pr)-[a:calculated_from] -> (pt)
MERGE(pr)-[b:calculated_from] -> (pu)
MERGE(n)-[c:has_property] -> (pr)
MERGE(n)-[d:used] -> (ps)
MERGE(n)-[r:has_property] -> (m)
MERGE(n)-[s:pressed_with] -> (o)
MERGE(n)-[t:coated_with] -> (p)
MERGE(n)-[u:drymilled_with] -> (q)
MERGE(n)-[v:dried_with] -> (nn)
MERGE(n)-[w:used_catalyst] -> (mm)
MERGE(n)-[x:used_solvant] -> (po)
MERGE(n)-[y:used_cat_iono_ratio] -> (pp)
MERGE(n)-[z:used_catalyst_loading] -> (pq)
"""
